apiVersion: v1
kind: Template
labels: {}
metadata:
  annotations:
    description: Template for setting up amq7-refarch OpenShift project
  labels:
    app: amq7-refarch
  name: amq7-refarch
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations: {}
    labels:
      app: amq-image
      project: amq7-refarch
    name: amq7-image
  spec:
    tags:
    - annotations:
        tags: "latest"
      from:
        kind: ImageStreamTag
        name: amq7-image
      name: "latest"
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations: {}
    labels:
      app: amq-image
      group: build
      project: amq7-refarch
      version: 1.0.0
    name: amq7-image
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: amq7-image:latest
    source:
      contextDir: S2I-Base-Image
      git:
        uri: https://github.com/RHSyseng/amq7.git
      images: []
      secrets: []
      type: Git
    strategy:
      dockerStrategy:
        noCache: true
        from:
          kind: DockerImage
          name: docker.io/fedora:26
        incremental: false
      type: Docker
    triggers:
    - imageChange:
      type: ImageChange